# Site settings
title: 付小森的森林
header-img: "img/facebook.jpg"
tagline: "cn"  
description: “付小森|A nice gift"  
baseurl: ""
url: "http://hinson.love"  

# About/contact
owner: 
  name: " Mason Fu"
  email: fu.tomorrow@gmail.com
  bio: "付小森的森林"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  itomorrow
twitter_username: itomorrow
github_username: itomorrow
facebook_username: itomorrow
weibo_username: rider_on_the_wheel 
zhihu_username: itomorrow

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
# permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
relative_permalinks: false

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Mason Fu"
      header-img: "img/facebook.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : rider_on_the_wheel
  disqus :
      short_name : rider_on_the_wheel

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
